--[[
 * File Name: startup.lua
 * Author: Kayne Ruse
 * Date: 5/9/2012
 * Copyright: (c) Kayne Ruse 2012
 *
 * This software is provided 'as-is', without any express or implied
 * warranty. In no event will the authors be held liable for any damages
 * arising from the use of this software.
 *
 * Permission is granted to anyone to use this software for any purpose,
 * including commercial applications, and to alter it and redistribute it
 * freely, subject to the following restrictions:
 *
 * 1. The origin of this software must not be misrepresented; you must not
 * claim that you wrote the original software. If you use this software
 * in a product, an acknowledgment in the product documentation would be
 * appreciated but is not required.
 *
 * 2. Altered source versions must be plainly marked as such, and must not be
 * misrepresented as being the original software.
 *
 * 3. This notice may not be removed or altered from any source
 * distribution.
 *
 * Description:
 *     ...
--]]

--Do not edit this file unless you know what you are doing!!

--configure the outputs
consoleprint = print
terminalprint = terminal.print
print = terminal.print --shortcut


--msg
consoleprint("--Running startup script...")


--setup the directory paths
dir = {}
dir["rsc"] = "rsc\\"


dir["map"] = dir["rsc"] .. "maps\\"
dir["brush"] = dir["rsc"] .. "brushes\\"
dir["filter"] = dir["rsc"] .. "filters\\"
dir["script"] = dir["rsc"] .. "scripts\\"
dir["tileset"] = dir["rsc"] .. "tilesets\\"
dir["font"] = dir["rsc"] .. "fonts\\"


--load the standard scripts
dofile(dir["brush"] .. "brush.lua")
dofile(dir["script"] .. "save_format.lua")
dofile(dir["filter"] .. "filter.lua")


--set the screensize
screen = {}
screen.w = 800
screen.h = 600
screen.fullscreen = false


--set the standard font
terminal.font = {} --just for the hell of it
terminal.font.fname = dir["font"] .. "pokemon_dark_font.bmp"
terminal.font.x = 16
terminal.font.y = 16
terminal.font.w = 16
terminal.font.h = 16


--useful debugging functions
function debugtable(t)
	for k, v in pairs(t) do
		consoleprint(k,v)
	end
end

function new(fname, x, y, l, w, h)
	tileset.load(dir["tileset"] .. fname, w, h)
	map.load(x, y, l)
	map.filllayer(1, 1)
end

--msg
consoleprint("--Finished")

--you can edit anything below this line

---[[default config
tileset.load(dir["tileset"] .. "terrain.bmp", 32, 32)
map.load(40,40,3)
fill(14)
--]]

