--Do not edit this file unless you know what you are doing!!

--configure the outputs
consoleprint = print
terminalprint = terminal.print
print = terminal.print --shortcut


--msg
consoleprint("--Running startup script...")


--setup the directory paths
dir = {}
dir["rsc"] = "rsc\\"


dir["map"] = dir["rsc"] .. "maps\\"
dir["brush"] = dir["rsc"] .. "brushes\\"
dir["filter"] = dir["rsc"] .. "filters\\"
dir["script"] = dir["rsc"] .. "scripts\\"
dir["tileset"] = dir["rsc"] .. "tilesets\\"
dir["font"] = dir["rsc"] .. "fonts\\"


--load the standard scripts
dofile(dir["brush"] .. "brush.lua")
dofile(dir["script"] .. "save_format.lua")


--set the screensize (not yet implemented)
--screen.w = 640
--screen.h = 480
--screen.fullscreen = false


--set the standard font
terminal.font = {} --just for the hell of it
terminal.font.fname = dir["font"] .. "pokemon_dark_font_skinny.bmp"
terminal.font.x = 16
terminal.font.y = 16
terminal.font.w = 8
terminal.font.h = 16


--useful debugging functions
function map.fill(v)
	map.filllayer(1, v)
end

function map.filllayer(l, v)
	if l < 1 or l > map.getlcount()	then
		print("Layer to fill out of range")
		return
	end
	
	for i = 1, map.getxcount() do
		for j = 1, map.getycount() do
			map.settile(i,j,l,v)
		end
	end
end

function debugtable(t)
	for k, v in pairs(t) do
		consoleprint(k,v)
	end
end


--default config
--tileset.load("terrain.bmp", 32, 32)
--map.load(40,40,3)
--map.fill(14)


load("bksave.txt")


--msg
consoleprint("--Finished")

--you can add more below this line
